// 이 파일은 워크스페이스 UI 문구 상수를 정의합니다.
export const copy = {
  auth: {
    callbackDescription:
      "This baseline route captures callback parameters and keeps provider integration deferred.",
    title: "Auth Callback"
  },
  persistence: {
    addDrawerItem: "Add Drawer Item",
    addEpisodes: "Add Episodes",
    authenticatedEmptyState:
      "No cloud projects exist for this account yet. Create your first project to start editing.",
    addToFolder: "Add to Folder",
    addSampleNode: "Add Sample Node",
    attachHere: "Attach Here",
    attachObjectToNode: "Insert Into Selected Node",
    cancel: "Cancel",
    closeSidebar: "Close Sidebar",
    cloudStatusLabel: "Cloud Status",
    createNode: "Create Node",
    createProject: "Create Project",
    delete: "Delete",
    deleteObject: "Delete Object",
    deleteConfirmation:
      "This node and all of its child nodes will be deleted together. Do you want to delete them?",
    detailEditorClosed: "Choose node or object details when you want deeper editing.",
    editDetails: "Edit Details",
    closeDetails: "Close Details",
    episodeDeleteConfirmation:
      "This episode will be removed together with its canvas nodes and drawer items. Do you want to delete it?",
    episodeDeleteLocked:
      "Keep at least one episode in the project. Create another episode before deleting this one.",
    fixed: "Fixed",
    fold: "Fold",
    hideSavedKeywords: "Hide Saved Keywords",
    drawerClosed: "Drawer closed",
    drawerOpen: "Drawer open",
    empty: "Empty",
    guestMode: "Guest mode keeps work in local cache only.",
    guestEmptyState:
      "No guest project is open yet. Create your first local episode or sign in to load account projects.",
    important: "Important",
    keywordCloudEmpty: "No keyword suggestions are available yet for this node.",
    keywordSelectionHint: "Select one or more keywords, then save them or unlock sentence suggestions.",
    keywordSuggestions: "Keyword Suggestions",
    keywordMode: "Keywords",
    keywordRefresh: "Refresh Cloud",
    more: "More",
    recommendationFailed: "Recommendation help is unavailable right now.",
    revealSavedKeywords: "Reveal Saved Keywords",
    saveKeywords: "Save Keywords",
    savedKeywords: "Saved Keywords",
    sentenceSuggestions: "Sentence Suggestions",
    moveToDrawer: "Send to Drawer",
    placeDraft: "Drag into any lane, or click a lane to place it.",
    openSidebar: "Open Sidebar",
    recoverFromCloud: "Recover From Cloud",
    restoreToCanvas: "Return to Canvas",
    removeObjectFromNode: "Remove From Selected Node",
    rewire: "Rewire",
    reloadLocal: "Reload From Cache",
    renameEpisode: "Rename",
    renameObject: "Rename Object",
    saveEpisode: "Save Episode",
    saveNode: "Save Node",
    saveObject: "Save Object",
    searchStories: "Search",
    signIn: "Sign In",
    signingIn: "Signing In",
    signInUnavailable:
      "Sign-in is unavailable. Set VITE_GOOGLE_CLIENT_ID (and backend GOOGLE_CLIENT_ID) to enable Google sign-in.",
    signInWithGoogleNotConfigured:
      "Google sign-in is not configured. Configure both frontend and backend Google client IDs.",
    signInWithGoogle: "Sign in with Google",
    signOut: "Sign Out",
    dissolveEpisode: "Dissolve",
    folderEpisode: "Folder",
    textMode: "Text",
    enterFullscreen: "Enter Fullscreen",
    exitFullscreen: "Exit Fullscreen",
    sortStories: "Sort",
    toggleDrawer: "Temporary Drawer",
    unfold: "Unfold",
    unfix: "Unfix",
    unpinEpisode: "Unpin",
    useSentence: "Use Sentence",
    undo: "Undo",
    redo: "Redo",
    pinEpisode: "Pin",
    pinObject: "Pin Object",
    unpinObject: "Unpin Object"
  },
  workspace: {
    brand: "ARIAD",
    attachedObjects: "Attached Objects",
    canvas: "Canvas",
    createObject: "New Object",
    detailLane: "Minor Detail Lane",
    details: "Detail Panel",
    drawer: "Temporary Drawer",
    inlineEditor:
      "Primary editing stays on the canvas. Open the right panel only when you need deeper detail editing.",
    majorLane: "Major Event Lane",
    minorLane: "Minor Event Lane",
    newEpisode: "New Episode",
    newFolder: "New Folder",
    newFolderPlaceholder: "Name this folder",
    noObjectsFound: "No reference objects match this search yet.",
    noFoldersYet: "Create a folder first.",
    objectCategory: "Category",
    objectEpisode: "Owned Episode",
    objectName: "Object Name",
    objectEpisodeMissing: "Unknown Episode",
    objects: "Object Library",
    objectScopeHint:
      "Reference objects are owned by episodes, and folder members can reuse each other by reference.",
    objectSearch: "Search Objects",
    objectSearchPlaceholder: "Search object's name",
    objectAttached: "Attached",
    objectSort: "Sort Objects",
    objectSortNameAsc: "A to Z",
    objectSortNameDesc: "Z to A",
    objectSortOldest: "Old to Recent",
    objectSortRecent: "Recent to Old",
    objectSortUsageAsc: "Least Used",
    objectSortUsageDesc: "Most Used",
    objectSummary: "Information",
    openObjectDetails: "Open Object Details",
    profile: "Profile",
    createFolder: "Create Folder",
    recentStories: "Recent Stories",
    recentStoriesEmpty: "No stories or folders match this search yet.",
    storySearchPlaceholder: "Search stories or folders",
    folderEmpty: "No stories are in this folder yet.",
    selectedObject: "Selected Object",
    title: "ARIAD Workspace",
    utilities: "More",
    utilitiesHint: "Account and recovery actions stay tucked away until you need them."
  }
} as const;
