const englishCopy = {
  auth: {
    callbackDescription:
      "This baseline route captures callback parameters and keeps provider integration deferred.",
    title: "Auth Callback"
  },
  persistence: {
    addDrawerItem: "Add Drawer Item",
    addEpisodes: "Add Episodes",
    addToFolder: "Add to Folder",
    addSampleNode: "Add Sample Node",
    attachHere: "Attach Here",
    attachObjectToNode: "Insert Into Selected Node",
    cancel: "Cancel",
    closeSidebar: "Close Sidebar",
    cloudStatusLabel: "Cloud Status",
    createNode: "Create Node",
    delete: "Delete",
    deleteObject: "Delete Object",
    deleteConfirmation:
      "This node and all of its child nodes will be deleted together. Do you want to delete them?",
    detailEditorClosed: "Choose node or object details when you want deeper editing.",
    editDetails: "Edit Details",
    closeDetails: "Close Details",
    episodeDeleteConfirmation:
      "This episode will be removed together with its canvas nodes and drawer items. Do you want to delete it?",
    episodeDeleteLocked:
      "Keep at least one episode in the project. Create another episode before deleting this one.",
    fixed: "Fixed",
    fold: "Fold",
    hideSavedKeywords: "Hide Saved Keywords",
    drawerClosed: "Drawer closed",
    drawerOpen: "Drawer open",
    empty: "Empty",
    guestMode: "Guest mode keeps work in local cache only.",
    important: "Important",
    keywordCloudEmpty: "No keyword suggestions are available yet for this node.",
    keywordSelectionHint: "Select one or more keywords, then save them or unlock sentence suggestions.",
    keywordSuggestions: "Keyword Suggestions",
    keywordMode: "Keywords",
    keywordRefresh: "Refresh Cloud",
    more: "More",
    objectNameRequired: "Object name is required.",
    recommendationFailed: "Recommendation help is unavailable right now.",
    revealSavedKeywords: "Reveal Saved Keywords",
    saveKeywords: "Save Keywords",
    savedKeywords: "Saved Keywords",
    sentenceSuggestions: "Sentence Suggestions",
    moveToDrawer: "Send to Drawer",
    placeDraft: "Drag into any lane, or click a lane to place it.",
    openSidebar: "Open Sidebar",
    recoverFromCloud: "Recover From Cloud",
    restoreToCanvas: "Return to Canvas",
    removeObjectFromNode: "Remove From Selected Node",
    rewire: "Rewire",
    reloadLocal: "Reload From Cache",
    renameEpisode: "Rename",
    renameObject: "Rename Object",
    saveEpisode: "Save Episode",
    saveNode: "Save Node",
    saveObject: "Save Object",
    searchStories: "Search",
    signIn: "Sign In",
    signOut: "Sign Out",
    dissolveEpisode: "Dissolve",
    folderEpisode: "Folder",
    textMode: "Text",
    enterFullscreen: "Enter Fullscreen",
    exitFullscreen: "Exit Fullscreen",
    sortStories: "Sort",
    toggleDrawer: "Temporary Drawer",
    unfold: "Unfold",
    unfix: "Unfix",
    unpinEpisode: "Unpin",
    useSentence: "Use Sentence",
    undo: "Undo",
    redo: "Redo",
    pinEpisode: "Pin",
    pinObject: "Pin Object",
    unpinObject: "Unpin Object"
  },
  workspace: {
    authenticated: "authenticated",
    brand: "ARIAD",
    attachedObjects: "Attached Objects",
    canvas: "Canvas",
    center: "Center",
    createObject: "New Object",
    currentEpisode: "Current episode",
    detailLane: "Minor Detail Lane",
    details: "Detail Panel",
    drawer: "Temporary Drawer",
    guest: "guest",
    guestWorkspace: "Guest workspace",
    inlineEditor:
      "Primary editing stays on the canvas. Open the right panel only when you need deeper detail editing.",
    language: "Language",
    linkedAccount: "Linked account",
    loadingWorkspace: "Loading the local persistence baseline for the active workspace.",
    majorLane: "Major Event Lane",
    minorLane: "Minor Event Lane",
    newEpisode: "New Episode",
    newFolder: "New Folder",
    newFolderPlaceholder: "Name this folder",
    noObjectsFound: "No reference objects match this episode search yet.",
    noFoldersYet: "Create a folder first.",
    nodeCountLabel: "Nodes",
    objectCategory: "Category",
    objectCategoryPerson: "Person",
    objectCategoryPlace: "Place",
    objectCategoryThing: "Thing",
    objectName: "Object Name",
    objects: "Object Library",
    objectScopeHint:
      "Reference objects are separated by episode and never move into the temporary drawer.",
    objectSearch: "Search Objects",
    objectSearchPlaceholder: "Search object's name",
    objectAttached: "Attached",
    objectSort: "Sort Objects",
    objectSortNameAsc: "A to Z",
    objectSortNameDesc: "Z to A",
    objectSortOldest: "Old to Recent",
    objectSortRecent: "Recent to Old",
    objectSortUsageAsc: "Least Used",
    objectSortUsageDesc: "Most Used",
    objectSummary: "Information",
    openObjectDetails: "Open Object Details",
    profile: "Profile",
    createFolder: "Create Folder",
    recentStories: "Recent Stories",
    recentStoriesEmpty: "No stories or folders match this search yet.",
    resetZoom: "Reset Zoom",
    resizeFromBottom: "Resize from bottom",
    resizeFromBottomLeft: "Resize from bottom left",
    resizeFromBottomRight: "Resize from bottom right",
    resizeFromLeft: "Resize from left",
    resizeFromRight: "Resize from right",
    resizeFromTop: "Resize from top",
    resizeFromTopLeft: "Resize from top left",
    resizeFromTopRight: "Resize from top right",
    storySearchPlaceholder: "Search stories or folders",
    folderEmpty: "No stories are in this folder yet.",
    selectedObject: "Selected Object",
    title: "ARIAD Workspace",
    typeTheBeat: "Type the beat",
    useAsObjectPrefix: "Use",
    useAsObjectSuffix: "as object",
    utilities: "More",
    utilitiesHint: "Account and recovery actions stay tucked away until you need them.",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out"
  }
};

export type WorkspaceCopy = typeof englishCopy;
export type WorkspaceLanguage = "en" | "ko" | "ja";

const koreanCopy: WorkspaceCopy = {
  auth: {
    callbackDescription:
      "이 기본 경로는 공급자 연동 없이 콜백 파라미터를 보관합니다.",
    title: "인증 콜백"
  },
  persistence: {
    addDrawerItem: "드로어 항목 추가",
    addEpisodes: "에피소드 추가",
    addToFolder: "폴더에 추가",
    addSampleNode: "샘플 노드 추가",
    attachHere: "여기에 연결",
    attachObjectToNode: "선택한 노드에 삽입",
    cancel: "취소",
    closeSidebar: "사이드바 닫기",
    cloudStatusLabel: "클라우드 상태",
    createNode: "노드 만들기",
    delete: "삭제",
    deleteObject: "오브젝트 삭제",
    deleteConfirmation:
      "이 노드와 모든 하위 노드가 함께 삭제됩니다. 삭제할까요?",
    detailEditorClosed: "더 자세히 편집하려면 노드나 오브젝트 세부 정보를 선택하세요.",
    editDetails: "세부 정보 편집",
    closeDetails: "세부 정보 닫기",
    episodeDeleteConfirmation:
      "이 에피소드는 캔버스 노드와 드로어 항목까지 함께 제거됩니다. 삭제할까요?",
    episodeDeleteLocked:
      "프로젝트에는 최소 한 개의 에피소드가 필요합니다. 삭제하기 전에 다른 에피소드를 만드세요.",
    fixed: "고정",
    fold: "접기",
    hideSavedKeywords: "저장 키워드 숨기기",
    drawerClosed: "드로어 닫힘",
    drawerOpen: "드로어 열림",
    empty: "비어 있음",
    guestMode: "게스트 모드는 작업을 로컬 캐시에만 보관합니다.",
    important: "중요",
    keywordCloudEmpty: "이 노드에 사용할 키워드 제안이 아직 없습니다.",
    keywordSelectionHint: "하나 이상의 키워드를 선택한 뒤 저장하거나 문장 제안을 여세요.",
    keywordSuggestions: "키워드 제안",
    keywordMode: "키워드",
    keywordRefresh: "클라우드 새로고침",
    more: "더 보기",
    objectNameRequired: "오브젝트 이름이 필요합니다.",
    recommendationFailed: "지금은 추천 도움을 사용할 수 없습니다.",
    revealSavedKeywords: "저장 키워드 보기",
    saveKeywords: "키워드 저장",
    savedKeywords: "저장된 키워드",
    sentenceSuggestions: "문장 제안",
    moveToDrawer: "드로어로 보내기",
    placeDraft: "아무 레인으로 드래그하거나 레인을 클릭해 배치하세요.",
    openSidebar: "사이드바 열기",
    recoverFromCloud: "클라우드에서 복구",
    restoreToCanvas: "캔버스로 되돌리기",
    removeObjectFromNode: "선택한 노드에서 제거",
    rewire: "다시 연결",
    reloadLocal: "캐시에서 다시 불러오기",
    renameEpisode: "이름 변경",
    renameObject: "오브젝트 이름 변경",
    saveEpisode: "에피소드 저장",
    saveNode: "노드 저장",
    saveObject: "오브젝트 저장",
    searchStories: "검색",
    signIn: "로그인",
    signOut: "로그아웃",
    dissolveEpisode: "분리",
    folderEpisode: "폴더",
    textMode: "텍스트",
    enterFullscreen: "전체 화면",
    exitFullscreen: "전체 화면 종료",
    sortStories: "정렬",
    toggleDrawer: "임시 드로어",
    unfold: "펼치기",
    unfix: "고정 해제",
    unpinEpisode: "고정 해제",
    useSentence: "문장 사용",
    undo: "실행 취소",
    redo: "다시 실행",
    pinEpisode: "고정",
    pinObject: "오브젝트 고정",
    unpinObject: "오브젝트 고정 해제"
  },
  workspace: {
    authenticated: "인증됨",
    brand: "ARIAD",
    attachedObjects: "연결된 오브젝트",
    canvas: "캔버스",
    center: "중앙",
    createObject: "새 오브젝트",
    currentEpisode: "현재 에피소드",
    detailLane: "세부 이벤트 레인",
    details: "세부 패널",
    drawer: "임시 드로어",
    guest: "게스트",
    guestWorkspace: "게스트 워크스페이스",
    inlineEditor:
      "주요 편집은 캔버스에서 진행됩니다. 더 깊은 편집이 필요할 때만 오른쪽 패널을 여세요.",
    language: "언어",
    linkedAccount: "연결된 계정",
    loadingWorkspace: "활성 워크스페이스의 로컬 저장 기준을 불러오는 중입니다.",
    majorLane: "주요 이벤트 레인",
    minorLane: "보조 이벤트 레인",
    newEpisode: "새 에피소드",
    newFolder: "새 폴더",
    newFolderPlaceholder: "폴더 이름",
    noObjectsFound: "이 에피소드 검색과 일치하는 참조 오브젝트가 아직 없습니다.",
    noFoldersYet: "먼저 폴더를 만드세요.",
    nodeCountLabel: "노드",
    objectCategory: "카테고리",
    objectCategoryPerson: "인물",
    objectCategoryPlace: "장소",
    objectCategoryThing: "사물",
    objectName: "오브젝트 이름",
    objects: "오브젝트 라이브러리",
    objectScopeHint:
      "참조 오브젝트는 에피소드별로 분리되며 임시 드로어로 이동하지 않습니다.",
    objectSearch: "오브젝트 검색",
    objectSearchPlaceholder: "오브젝트 이름 검색",
    objectAttached: "연결됨",
    objectSort: "오브젝트 정렬",
    objectSortNameAsc: "가나다순",
    objectSortNameDesc: "역순",
    objectSortOldest: "오래된 순",
    objectSortRecent: "최근 순",
    objectSortUsageAsc: "적게 사용",
    objectSortUsageDesc: "많이 사용",
    objectSummary: "정보",
    openObjectDetails: "오브젝트 세부 정보 열기",
    profile: "프로필",
    createFolder: "폴더 만들기",
    recentStories: "최근 스토리",
    recentStoriesEmpty: "이 검색과 일치하는 스토리나 폴더가 아직 없습니다.",
    resetZoom: "줌 초기화",
    resizeFromBottom: "아래쪽에서 크기 조절",
    resizeFromBottomLeft: "왼쪽 아래에서 크기 조절",
    resizeFromBottomRight: "오른쪽 아래에서 크기 조절",
    resizeFromLeft: "왼쪽에서 크기 조절",
    resizeFromRight: "오른쪽에서 크기 조절",
    resizeFromTop: "위쪽에서 크기 조절",
    resizeFromTopLeft: "왼쪽 위에서 크기 조절",
    resizeFromTopRight: "오른쪽 위에서 크기 조절",
    storySearchPlaceholder: "스토리 또는 폴더 검색",
    folderEmpty: "이 폴더에는 아직 스토리가 없습니다.",
    selectedObject: "선택한 오브젝트",
    title: "ARIAD 워크스페이스",
    typeTheBeat: "비트를 입력하세요",
    useAsObjectPrefix: "다음 이름을 오브젝트로 사용:",
    useAsObjectSuffix: "",
    utilities: "더 보기",
    utilitiesHint: "계정과 복구 작업은 필요할 때만 열 수 있습니다.",
    zoomIn: "확대",
    zoomOut: "축소"
  }
};

const japaneseCopy: WorkspaceCopy = {
  auth: {
    callbackDescription:
      "この基本ルートは、プロバイダー連携なしでコールバックパラメーターを保持します。",
    title: "認証コールバック"
  },
  persistence: {
    addDrawerItem: "ドロワー項目を追加",
    addEpisodes: "エピソードを追加",
    addToFolder: "フォルダーに追加",
    addSampleNode: "サンプルノードを追加",
    attachHere: "ここに接続",
    attachObjectToNode: "選択中のノードに挿入",
    cancel: "キャンセル",
    closeSidebar: "サイドバーを閉じる",
    cloudStatusLabel: "クラウド状態",
    createNode: "ノード作成",
    delete: "削除",
    deleteObject: "オブジェクト削除",
    deleteConfirmation:
      "このノードとすべての子ノードが一緒に削除されます。削除しますか？",
    detailEditorClosed: "詳しく編集したいときは、ノードまたはオブジェクトの詳細を選択してください。",
    editDetails: "詳細を編集",
    closeDetails: "詳細を閉じる",
    episodeDeleteConfirmation:
      "このエピソードはキャンバスノードとドロワー項目ごと削除されます。削除しますか？",
    episodeDeleteLocked:
      "プロジェクトには少なくとも1つのエピソードが必要です。削除する前に別のエピソードを作成してください。",
    fixed: "固定",
    fold: "折りたたむ",
    hideSavedKeywords: "保存済みキーワードを隠す",
    drawerClosed: "ドロワー閉",
    drawerOpen: "ドロワー開",
    empty: "空",
    guestMode: "ゲストモードでは作業をローカルキャッシュのみに保存します。",
    important: "重要",
    keywordCloudEmpty: "このノードのキーワード候補はまだありません。",
    keywordSelectionHint: "キーワードを1つ以上選び、保存するか文候補を開いてください。",
    keywordSuggestions: "キーワード候補",
    keywordMode: "キーワード",
    keywordRefresh: "クラウド更新",
    more: "その他",
    objectNameRequired: "オブジェクト名が必要です。",
    recommendationFailed: "現在、推薦機能を利用できません。",
    revealSavedKeywords: "保存済みキーワードを表示",
    saveKeywords: "キーワード保存",
    savedKeywords: "保存済みキーワード",
    sentenceSuggestions: "文候補",
    moveToDrawer: "ドロワーへ送る",
    placeDraft: "任意のレーンへドラッグするか、レーンをクリックして配置してください。",
    openSidebar: "サイドバーを開く",
    recoverFromCloud: "クラウドから復元",
    restoreToCanvas: "キャンバスに戻す",
    removeObjectFromNode: "選択中のノードから削除",
    rewire: "接続変更",
    reloadLocal: "キャッシュから再読込",
    renameEpisode: "名前変更",
    renameObject: "オブジェクト名変更",
    saveEpisode: "エピソード保存",
    saveNode: "ノード保存",
    saveObject: "オブジェクト保存",
    searchStories: "検索",
    signIn: "サインイン",
    signOut: "サインアウト",
    dissolveEpisode: "分離",
    folderEpisode: "フォルダー",
    textMode: "テキスト",
    enterFullscreen: "全画面表示",
    exitFullscreen: "全画面終了",
    sortStories: "並べ替え",
    toggleDrawer: "一時ドロワー",
    unfold: "展開",
    unfix: "固定解除",
    unpinEpisode: "ピン解除",
    useSentence: "文を使用",
    undo: "元に戻す",
    redo: "やり直す",
    pinEpisode: "ピン留め",
    pinObject: "オブジェクトをピン留め",
    unpinObject: "オブジェクトのピン解除"
  },
  workspace: {
    authenticated: "認証済み",
    brand: "ARIAD",
    attachedObjects: "接続済みオブジェクト",
    canvas: "キャンバス",
    center: "中央",
    createObject: "新規オブジェクト",
    currentEpisode: "現在のエピソード",
    detailLane: "詳細イベントレーン",
    details: "詳細パネル",
    drawer: "一時ドロワー",
    guest: "ゲスト",
    guestWorkspace: "ゲストワークスペース",
    inlineEditor:
      "主な編集はキャンバスで行います。より深く編集するときだけ右パネルを開いてください。",
    language: "言語",
    linkedAccount: "接続済みアカウント",
    loadingWorkspace: "アクティブなワークスペースのローカル保存基盤を読み込んでいます。",
    majorLane: "主要イベントレーン",
    minorLane: "補助イベントレーン",
    newEpisode: "新規エピソード",
    newFolder: "新規フォルダー",
    newFolderPlaceholder: "フォルダー名",
    noObjectsFound: "このエピソード検索に一致する参照オブジェクトはまだありません。",
    noFoldersYet: "先にフォルダーを作成してください。",
    nodeCountLabel: "ノード",
    objectCategory: "カテゴリー",
    objectCategoryPerson: "人物",
    objectCategoryPlace: "場所",
    objectCategoryThing: "物",
    objectName: "オブジェクト名",
    objects: "オブジェクトライブラリ",
    objectScopeHint:
      "参照オブジェクトはエピソードごとに分かれ、一時ドロワーには移動しません。",
    objectSearch: "オブジェクト検索",
    objectSearchPlaceholder: "オブジェクト名を検索",
    objectAttached: "接続済み",
    objectSort: "オブジェクト並べ替え",
    objectSortNameAsc: "昇順",
    objectSortNameDesc: "降順",
    objectSortOldest: "古い順",
    objectSortRecent: "新しい順",
    objectSortUsageAsc: "使用少ない順",
    objectSortUsageDesc: "使用多い順",
    objectSummary: "情報",
    openObjectDetails: "オブジェクト詳細を開く",
    profile: "プロフィール",
    createFolder: "フォルダー作成",
    recentStories: "最近のストーリー",
    recentStoriesEmpty: "この検索に一致するストーリーやフォルダーはまだありません。",
    resetZoom: "ズームをリセット",
    resizeFromBottom: "下からサイズ変更",
    resizeFromBottomLeft: "左下からサイズ変更",
    resizeFromBottomRight: "右下からサイズ変更",
    resizeFromLeft: "左からサイズ変更",
    resizeFromRight: "右からサイズ変更",
    resizeFromTop: "上からサイズ変更",
    resizeFromTopLeft: "左上からサイズ変更",
    resizeFromTopRight: "右上からサイズ変更",
    storySearchPlaceholder: "ストーリーまたはフォルダーを検索",
    folderEmpty: "このフォルダーにはまだストーリーがありません。",
    selectedObject: "選択中のオブジェクト",
    title: "ARIAD ワークスペース",
    typeTheBeat: "ビートを入力",
    useAsObjectPrefix: "オブジェクトとして使用:",
    useAsObjectSuffix: "",
    utilities: "その他",
    utilitiesHint: "アカウントと復元操作は必要なときだけ表示されます。",
    zoomIn: "拡大",
    zoomOut: "縮小"
  }
};

export const defaultLanguage: WorkspaceLanguage = "en";
export const copy = englishCopy;
export const copyCatalog: Record<WorkspaceLanguage, WorkspaceCopy> = {
  en: englishCopy,
  ja: japaneseCopy,
  ko: koreanCopy
};

export const languageHtmlCodes: Record<WorkspaceLanguage, string> = {
  en: "en",
  ja: "ja",
  ko: "ko"
};

export const languageOptions: Array<{
  label: string;
  nativeLabel: string;
  value: WorkspaceLanguage;
}> = [
  {
    label: "English",
    nativeLabel: "English",
    value: "en"
  },
  {
    label: "Korean",
    nativeLabel: "한국어",
    value: "ko"
  },
  {
    label: "Japanese",
    nativeLabel: "日本語",
    value: "ja"
  }
];

export function isWorkspaceLanguage(value: string | null): value is WorkspaceLanguage {
  return value === "en" || value === "ko" || value === "ja";
}
